title: Persoonlijke blogsite
author: Roderik Egberink
email: r.egberink@mlgm.nl
description: > # this means to ignore newlines until "baseurl:"
  Persoonlijke blog van Roderik Egberink
  Gebruikt voor het vak digitale technologie op het Montessori Lyceum Gooise Meren

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
